# Generated by Django 3.0.8 on 2020-08-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='context',
            field=models.TextField(),
        ),
    ]
