# Generated by Django 3.0.8 on 2020-08-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0003_lesson_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video',
            new_name='videofile',
        ),
    ]
