# Generated by Django 3.0.8 on 2020-08-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0004_auto_20200821_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='video'),
        ),
    ]
