# Generated by Django 3.0.8 on 2020-08-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0005_auto_20200821_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='videofile',
            new_name='video',
        ),
    ]
